### ISSUE TITLE
Running the openssl speed command does not respond.

### ISSUE THREAD

**Issue by wangzengliang123** [kunpengcompute/KAE#24]
OS : openEuler 22.03 
CPU: Kunpeng920 5250
openssl 1.1.1m
Reproduction Procedure：
 1、export  OPENSSL_CONF="/home/openssl.cnf"
 2、 for i in {1..1000};do taskset -c 0-1 openssl speed -engine kae -evp sm4-cbc -seconds 1 -multi 128;done
Remarks conf：
openssl_conf=openssl_def
[openssl_def]
engines=engine_section
[engine_section]
kae=kae_section
[kae_section]
dynamic_path=/usr/lib64/engines-1.1/kae.so
engine_id=kae

info:
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-70.oe2203.aarch64
(gdb) bt
#0  0x0000ffffad92ca3c in ?? () from /usr/lib64/libc.so.6
#1  0x0000ffffad932fac in pthread_mutex_lock () from /usr/lib64/libc.so.6
#2  0x0000ffffad8533ac in kae_queue_pool_destroy () from /usr/lib64/engines-1.1/kae.so
#3  0x0000ffffad841afc in wd_ciphers_init_qnode_pool () from /usr/lib64/engines-1.1/kae.so
#4  0x0000ffffad83aa9c in cipher_module_init () from /usr/lib64/engines-1.1/kae.so
#5  0x0000ffffad8552b4 in engine_init_child_at_fork_handler () from /usr/lib64/engines-1.1/kae.so
#6  0x0000ffffad967d24 in ?? () from /usr/lib64/libc.so.6
#7  0x0000ffffad9675f0 in fork () from /usr/lib64/libc.so.6
#8  0x000000000044e458 in do_multi (size_num=6, multi=128) at apps/speed.c:3550
#9  speed_main (argc=0, argv=<optimized out>) at apps/speed.c:1849
#10 0x000000000042f4b4 in do_cmd (prog=prog@entry=0x38bd3050, argc=argc@entry=9, argv=argv@entry=0xffffe8e4e5e0) at apps/openssl.c:570
#11 0x000000000041c938 in main (argc=9, argv=0xffffe8e4e5e0) at apps/openssl.c:189

**Comment by wangzengliang123** [comment]
KAE 1.3.11
